"""Scrapers immo-agent — gérés par Claude Code"""

# LeSiteImmo [✓]
# Bien'ici [✓]
# Immobilier.notaires.fr [✓]
# IAD France [✓]
# DVF (Demandes de Valeurs Foncières) [✓]
# ORPI [✓]
# Nestenn Immobilier [✓]
# SAFTI Immobilier [✓]
# L'Adresse Immobilier [✓]
# Figaro Immobilier [✓]
# Propriétés Privées [✓]
# Optimhome [✓]
# RE/MAX France [✓]
# megAgence [✓]
# Citya Immobilier [✓]
# Foncia Transaction [✓]
# Square Habitat (Crédit Agricole) [✓]
# SeLoger [✓]
# Properstar [✓]
# Laforêt Immobilier [✓]
# Arthur Immo [✓]
# ERA Immobilier [✓]
# EntreparticulierS [✓]
# Immonot (Notaires) [✓]
# Paru Vendu Immobilier [✓]
# Green-Acres [✓]
# Patrice Besse (demeures de caractère) [✓]
# Cabinet Le Nail (châteaux, manoirs, prestige) [✓]
# Terres et Demeures de France (caractère) [✓]
# Architecture de Collection [✓]
# French Property (acheteurs anglophones) [✓]
# Emile Garcin (prestige) [✓]
# Groupe Mercure (demeures de caractère) [✓]
# Dr House Immo (mandataires) [✓]
# eXp France (mandataires) [✓]
# 123webimmo (mandataires) [✓]
# MeilleursBiens (mandataires) [✓]
# Imkiz (agence en ligne) [✓]
# Liberkeys (agence en ligne) [✓]
# CIMM Immobilier (réseau) [✓]
# Le Tuc Immo (réseau) [✓]
# Transaxia Immobilier [✓]
# Immobilier France Ouest [✓]
# Hectares et Patrimoine [✓]
# Equidomain [✓]
# Ma-Propriete.fr [✓]
# Groupement Immobilier [✓]
# Proprietes Rurales [✓]
# Horse Immo [✓]
# Noovimo [✓]
# Declic Immo [✓]
# Coldwell Banker France [✓]
# Notaires Val de Loire (Chambre interdép.) [✓]
# Equirodi [✓]
# Cle France [✓]
# Agence Pollet (iii-immobilier) [✓]
# Sergic [✓]
# Maisons Bourgogne (Agence Prunier) [✓]
# IMMO de France (Procivis) [✓]
# My French House [✓]
# Val de Loire Sologne Sotheby's International Realty [✓]
# Cabinet Chevillon [✓]
# Cabinet Métais [✓]
# 72 Immobilier [✓]
# La Visite Immo [✓]
# Nicole Joubert [✓]
# Anou Immobilier [✓]
# Aviron Conseil Immobilier [✓]
# MDI Anjou-Maine [✓]
# Lucilia B. Immobilier [✓]
# Immomans [✓]
# FNAIM (portail adhérents) [✓]
# Century 21 France [✓]
# Immo Réseau (conseillers indépendants) [✓]
# Breton & Jeanneau Immobilier (Sarthe & Mayenne) [✓]