"""Scrapers immo-agent — gérés par Claude Code"""

# LeSiteImmo [✓]
# Bien'ici [✓]
# Immobilier.notaires.fr [✓]
# IAD France [✓]
# DVF (Demandes de Valeurs Foncières) [✓]
# ORPI [✓]
# Nestenn Immobilier [✓]
# SAFTI Immobilier [✓]
# L'Adresse Immobilier [✓]
# Figaro Immobilier [✓]
# Propriétés Privées [✓]
# Optimhome [✓]
# RE/MAX France [✓]
# megAgence [✓]
# Citya Immobilier [✓]
# Foncia Transaction [✓]
# Square Habitat (Crédit Agricole) [✓]
# SeLoger [✓]
# Properstar [✓]
# Laforêt Immobilier [✓]
# Arthur Immo [✓]
# ERA Immobilier [✓]
# EntreparticulierS [✓]
# Immonot (Notaires) [✓]
# Paru Vendu Immobilier [✓]
# Green-Acres [✓]
# Patrice Besse (demeures de caractère) [✓]
# Cabinet Le Nail (châteaux, manoirs, prestige) [✓]
# Terres et Demeures de France (caractère) [✓]
# Architecture de Collection [✓]
# French Property (acheteurs anglophones) [✓]
# Emile Garcin (prestige) [✓]
# Groupe Mercure (demeures de caractère) [✓]
# Dr House Immo (mandataires) [✓]
# eXp France (mandataires) [✓]
# 123webimmo (mandataires) [✓]
# MeilleursBiens (mandataires) [✓]
# Imkiz (agence en ligne) [✓]
# Liberkeys (agence en ligne) [✓]
# CIMM Immobilier (réseau) [✓]
# Le Tuc Immo (réseau) [✓]