"""Scrapers immo-agent — gérés par Claude Code"""

# LeSiteImmo [✓]
# Bien'ici [✓]
# Immobilier.notaires.fr [✓]
# IAD France [✓]
# DVF (Demandes de Valeurs Foncières) [✓]
# ORPI [✓]
# Nestenn Immobilier [✓]
# SAFTI Immobilier [✓]
# L'Adresse Immobilier [✓]
# Figaro Immobilier [✓]
# Propriétés Privées [✓]
# Optimhome [✓]
# RE/MAX France [✓]
# megAgence [✓]
# Citya Immobilier [✓]
# Foncia Transaction [✓]
# Square Habitat (Crédit Agricole) [✓]
# SeLoger [✓]
# Properstar [✓]
# Laforêt Immobilier [✓]
# Arthur Immo [✓]
# ERA Immobilier [✓]
# EntreparticulierS [✓]
# Immonot (Notaires) [✓]
# Paru Vendu Immobilier [✓]
# Green-Acres [✓]
# Patrice Besse (demeures de caractère) [✓]